<?php
$this->headTitle('Add Category');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('categories', ['action'=>'index']),
            'Admin'=>$this->url('categories', ['action'=>'admin']),
            'New'=>$this->url('categories', ['action'=>'add'])
            ]);

$form = $this->form;
$form->get('name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Category name'
    ]);
$form->get('status')->setAttributes([
    'class'=>'form-control'   
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>New Category</h1>

<p>
    Fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   