<?php
$this->headTitle('Edit Category');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('categories', ['action'=>'index']),
    'Admin' => $this->url('categories', ['action' => 'admin']),
    $category->getName() => $this->url('categories', ['action' => 'view', 'id' => $category->getId()]),
    'Edit Category' => $this->url('categories', ['action' => 'edit'])
]);

$form = $this->form;
$form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Category name'
]);

$form->get('status')->setAttributes([
    'class' => 'form-control'
]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->get('submit')->setValue('Save');
$form->prepare();

?>

<h1>Edit Category</h1>

<p>
    Fill out the following form and click the *Save* button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   