<?= $this->doctype() ?>
<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')

        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath().'/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))

        ?>

        <!-- Scripts -->
        <?=
                $this->inlineScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))

        ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Skeleton Application
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <!-- Navigation bar -->
                        <?php
                        // Initialize navbar items
                        $this->mainMenu()->setItems([
                            [
                                'id' => 'home',
                                'label' => 'Home',
                                'link' => $this->url('home')
                            ],
                            [
                                'id' => 'admin',
                                'label' => 'Admin',
                                'link' => $this->url('posts', ['action' => 'admin'])
                            ],
                            [
                                'id' => 'categories',
                                'label' => 'Categories',
                                'link' => $this->url('categories', ['action' => 'index'])
                            ],
                            [
                                'id' => 'about',
                                'label' => 'About',
                                'link' => $this->url('about')
                            ],
                        ]);

                        // Check if the activeMenuItemId passed to layout view model
                        // and if so, use it for setting active navbar item.
                        if (isset($activeMenuItemId)) {
                            $this->mainMenu()->setActiveItemId($activeMenuItemId);
                        }

                        // Render the navbar
                        echo $this->mainMenu()->render();

                        ?>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')

        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath().'/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))

        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))

        ?>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <!-- Page header -->
                <div class="col-md-4">
                    <div class="app-caption">ZF App</div>
                </div>                
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Navigation bar -->
                    <?php
                    // Initialize navbar items
                    $this->mainMenu()->setItems([
                        [
                            'id' => 'home',
                            'label' => 'Home',
                            'link' => $this->url('home')
                        ],
                        [
                            'id' => 'admin',
                            'label' => 'Admin',
                            'link' => $this->url('posts', ['action' => 'admin'])
                        ],
                        [
                            'id' => 'categories',
                            'label' => 'Categories',
                            'link' => $this->url('categories', ['action' => 'index'])
                        ],
                        [
                            'id' => 'about',
                            'label' => 'About',
                            'link' => $this->url('about')
                        ],
                    ]);

                    // Check if the activeMenuItemId passed to layout view model
                    // and if so, use it for setting active navbar item.
                    if (isset($activeMenuItemId)) {
                        $this->mainMenu()->setActiveItemId($activeMenuItemId);
                    }

                    // Render the navbar
                    echo $this->mainMenu()->render();

                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Breadcrumbs -->
                    <?= $this->pageBreadcrumbs()->render(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Page content placeholder -->
                    <?= $this->content; ?>
                </div>
            </div>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Your Company. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
